version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - checkout


      - run:
          name: Downloading npm dependencies
          command: npm install --save-dev

      - run:
          name: Building production static files
          command: npm run build

      - run:
          name: Install rsync
          command: sudo apt-get install -y rsync

      - run:
          name: Deploying to server
          command: ./scripts/deploy.sh